
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public sealed partial class Bridge_Config : Luban.BeanBase
{
    public Bridge_Config(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Name = _buf.ReadString();
        ResourceName = _buf.ReadString();
        Length = _buf.ReadInt();
        Width = _buf.ReadInt();
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);TrafficDirection = new System.Collections.Generic.List<System.Collections.Generic.List<int>>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { System.Collections.Generic.List<int> _e0;  {int n1 = System.Math.Min(_buf.ReadSize(), _buf.Size);_e0 = new System.Collections.Generic.List<int>(n1);for(var i1 = 0 ; i1 < n1 ; i1++) { int _e1;  _e1 = _buf.ReadInt(); _e0.Add(_e1);}} TrafficDirection.Add(_e0);}}
    }

    public static Bridge_Config DeserializeBridge_Config(ByteBuf _buf)
    {
        return new Bridge_Config(_buf);
    }

    /// <summary>
    /// 建筑id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 建筑名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 建筑资源名
    /// </summary>
    public readonly string ResourceName;
    /// <summary>
    /// 长度
    /// </summary>
    public readonly int Length;
    /// <summary>
    /// 宽度
    /// </summary>
    public readonly int Width;
    /// <summary>
    /// 通行方向
    /// </summary>
    public readonly System.Collections.Generic.List<System.Collections.Generic.List<int>> TrafficDirection;
   
    public const int __ID__ = 651467960;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "resourceName:" + ResourceName + ","
        + "length:" + Length + ","
        + "width:" + Width + ","
        + "trafficDirection:" + Luban.StringUtil.CollectionToString(TrafficDirection) + ","
        + "}";
    }
}

}
