
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg.building
{ 
    public enum FunctionType
    {
        /// <summary>
        /// 游客中心
        /// </summary>
        VisitorCenter = 1,
        /// <summary>
        /// 航站楼
        /// </summary>
        Airport = 2,
        /// <summary>
        /// 商店
        /// </summary>
        Shop = 3,
    }

} 

