
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public sealed partial class Building_Config : Luban.BeanBase
{
    public Building_Config(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Name = _buf.ReadString();
        ResourceName = _buf.ReadString();
        Length = _buf.ReadInt();
        Width = _buf.ReadInt();
        FunctionType = (building.FunctionType)_buf.ReadInt();
    }

    public static Building_Config DeserializeBuilding_Config(ByteBuf _buf)
    {
        return new Building_Config(_buf);
    }

    /// <summary>
    /// 建筑id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 建筑名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 建筑资源名
    /// </summary>
    public readonly string ResourceName;
    /// <summary>
    /// 长度
    /// </summary>
    public readonly int Length;
    /// <summary>
    /// 宽度
    /// </summary>
    public readonly int Width;
    /// <summary>
    /// 建筑类型
    /// </summary>
    public readonly building.FunctionType FunctionType;
   
    public const int __ID__ = 1848139565;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "resourceName:" + ResourceName + ","
        + "length:" + Length + ","
        + "width:" + Width + ","
        + "functionType:" + FunctionType + ","
        + "}";
    }
}

}
