
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public sealed partial class BuildingUnlock : Luban.BeanBase
{
    public BuildingUnlock(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);UnlockEffect = new System.Collections.Generic.List<zsEnum.UnlockEffect>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { zsEnum.UnlockEffect _e0;  _e0 = (zsEnum.UnlockEffect)_buf.ReadInt(); UnlockEffect.Add(_e0);}}
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);Value1 = new System.Collections.Generic.List<zsEnum.BuildingSubtype>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { zsEnum.BuildingSubtype _e0;  _e0 = (zsEnum.BuildingSubtype)_buf.ReadInt(); Value1.Add(_e0);}}
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);Value2 = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); Value2.Add(_e0);}}
    }

    public static BuildingUnlock DeserializeBuildingUnlock(ByteBuf _buf)
    {
        return new BuildingUnlock(_buf);
    }

    /// <summary>
    /// 建筑id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 解锁效果
    /// </summary>
    public readonly System.Collections.Generic.List<zsEnum.UnlockEffect> UnlockEffect;
    /// <summary>
    /// 参数1(对应解锁效果，建筑小类枚举）
    /// </summary>
    public readonly System.Collections.Generic.List<zsEnum.BuildingSubtype> Value1;
    /// <summary>
    /// 参数2（具体参数，Value1有值对应Value1，没值对应解锁效果）
    /// </summary>
    public readonly System.Collections.Generic.List<int> Value2;
   
    public const int __ID__ = -187051208;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "UnlockEffect:" + Luban.StringUtil.CollectionToString(UnlockEffect) + ","
        + "Value1:" + Luban.StringUtil.CollectionToString(Value1) + ","
        + "Value2:" + Luban.StringUtil.CollectionToString(Value2) + ","
        + "}";
    }
}

}
