
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public sealed partial class Build : Luban.BeanBase
{
    public Build(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Name = _buf.ReadString();
        ResourceName = _buf.ReadString();
        Length = _buf.ReadInt();
        Width = _buf.ReadInt();
        BuildingType = (zsEnum.BuildingType)_buf.ReadInt();
        BuildingSubtype = (zsEnum.BuildingSubtype)_buf.ReadInt();
        Storable = _buf.ReadBool();
        Orientation = (zsEnum.Orientation)_buf.ReadInt();
        DemandOccupation = (zsEnum.Profession)_buf.ReadInt();
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);BuildingTag = new System.Collections.Generic.List<zsEnum.PreferenceTag>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { zsEnum.PreferenceTag _e0;  _e0 = (zsEnum.PreferenceTag)_buf.ReadInt(); BuildingTag.Add(_e0);}}
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);IslandAffinity = new System.Collections.Generic.List<System.Collections.Generic.List<int>>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { System.Collections.Generic.List<int> _e0;  {int n1 = System.Math.Min(_buf.ReadSize(), _buf.Size);_e0 = new System.Collections.Generic.List<int>(n1);for(var i1 = 0 ; i1 < n1 ; i1++) { int _e1;  _e1 = _buf.ReadInt(); _e0.Add(_e1);}} IslandAffinity.Add(_e0);}}
        AttrType = _buf.ReadString();
    }

    public static Build DeserializeBuild(ByteBuf _buf)
    {
        return new Build(_buf);
    }

    /// <summary>
    /// 建筑id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 建筑名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 建筑资源名
    /// </summary>
    public readonly string ResourceName;
    /// <summary>
    /// 长度
    /// </summary>
    public readonly int Length;
    /// <summary>
    /// 宽度
    /// </summary>
    public readonly int Width;
    /// <summary>
    /// 建筑大类
    /// </summary>
    public readonly zsEnum.BuildingType BuildingType;
    /// <summary>
    /// 建筑小类
    /// </summary>
    public readonly zsEnum.BuildingSubtype BuildingSubtype;
    /// <summary>
    /// 可否存放
    /// </summary>
    public readonly bool Storable;
    /// <summary>
    /// 模型朝向
    /// </summary>
    public readonly zsEnum.Orientation Orientation;
    /// <summary>
    /// 需求职业
    /// </summary>
    public readonly zsEnum.Profession DemandOccupation;
    /// <summary>
    /// 建筑标签
    /// </summary>
    public readonly System.Collections.Generic.List<zsEnum.PreferenceTag> BuildingTag;
    /// <summary>
    /// 岛屿亲和
    /// </summary>
    public readonly System.Collections.Generic.List<System.Collections.Generic.List<int>> IslandAffinity;
    /// <summary>
    /// 属性影响类型
    /// </summary>
    public readonly string AttrType;
   
    public const int __ID__ = 64542286;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
        
        
        
        
        
        
        
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "resourceName:" + ResourceName + ","
        + "length:" + Length + ","
        + "width:" + Width + ","
        + "BuildingType:" + BuildingType + ","
        + "BuildingSubtype:" + BuildingSubtype + ","
        + "Storable:" + Storable + ","
        + "Orientation:" + Orientation + ","
        + "DemandOccupation:" + DemandOccupation + ","
        + "BuildingTag:" + Luban.StringUtil.CollectionToString(BuildingTag) + ","
        + "IslandAffinity:" + Luban.StringUtil.CollectionToString(IslandAffinity) + ","
        + "AttrType:" + AttrType + ","
        + "}";
    }
}

}
