
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg.building
{ 
    public enum FunctionType
    {
        /// <summary>
        /// 游客中心
        /// </summary>
        VisitorCenter = 1,
        /// <summary>
        /// 航站楼
        /// </summary>
        Airport = 2,
        /// <summary>
        /// 工程署
        /// </summary>
        EngineeringDepartment = 3,
        /// <summary>
        /// 人才中心
        /// </summary>
        TalentCenter = 4,
        /// <summary>
        /// 商店
        /// </summary>
        Shop = 5,
        /// <summary>
        /// 工厂
        /// </summary>
        Factory = 6,
    }

} 

