
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public sealed partial class BuildingLevel : Luban.BeanBase
{
    public BuildingLevel(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Name = _buf.ReadString();
        BuildMsg = _buf.ReadString();
        BuildLevel = _buf.ReadInt();
        BuildingType = (zsEnum.BuildingType)_buf.ReadInt();
        BuildingSubtype = (zsEnum.BuildingSubtype)_buf.ReadInt();
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);BuildingTag = new System.Collections.Generic.List<zsEnum.PreferenceTag>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { zsEnum.PreferenceTag _e0;  _e0 = (zsEnum.PreferenceTag)_buf.ReadInt(); BuildingTag.Add(_e0);}}
        Prosperity = _buf.ReadInt();
        PowerConsumption = _buf.ReadInt();
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);IslandAffinity = new System.Collections.Generic.List<zsEnum.IslandType>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { zsEnum.IslandType _e0;  _e0 = (zsEnum.IslandType)_buf.ReadInt(); IslandAffinity.Add(_e0);}}
        JobSlots = _buf.ReadInt();
        DemandOccupation = (zsEnum.Profession)_buf.ReadInt();
        VisitorCapacity = _buf.ReadInt();
        DwellTime = _buf.ReadInt();
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);OutPut = new System.Collections.Generic.List<System.Collections.Generic.List<int>>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { System.Collections.Generic.List<int> _e0;  {int n1 = System.Math.Min(_buf.ReadSize(), _buf.Size);_e0 = new System.Collections.Generic.List<int>(n1);for(var i1 = 0 ; i1 < n1 ; i1++) { int _e1;  _e1 = _buf.ReadInt(); _e0.Add(_e1);}} OutPut.Add(_e0);}}
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);ItemCost = new System.Collections.Generic.List<System.Collections.Generic.List<int>>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { System.Collections.Generic.List<int> _e0;  {int n1 = System.Math.Min(_buf.ReadSize(), _buf.Size);_e0 = new System.Collections.Generic.List<int>(n1);for(var i1 = 0 ; i1 < n1 ; i1++) { int _e1;  _e1 = _buf.ReadInt(); _e0.Add(_e1);}} ItemCost.Add(_e0);}}
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);OutputStorage = new System.Collections.Generic.List<System.Collections.Generic.List<int>>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { System.Collections.Generic.List<int> _e0;  {int n1 = System.Math.Min(_buf.ReadSize(), _buf.Size);_e0 = new System.Collections.Generic.List<int>(n1);for(var i1 = 0 ; i1 < n1 ; i1++) { int _e1;  _e1 = _buf.ReadInt(); _e0.Add(_e1);}} OutputStorage.Add(_e0);}}
        OutputCycle = _buf.ReadInt();
        IconId = _buf.ReadString();
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);Anchor = new System.Collections.Generic.List<float>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { float _e0;  _e0 = _buf.ReadFloat(); Anchor.Add(_e0);}}
        Model = _buf.ReadString();
        Orientation = (zsEnum.Orientation)_buf.ReadInt();
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);UpCondition = new System.Collections.Generic.List<System.Collections.Generic.List<int>>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { System.Collections.Generic.List<int> _e0;  {int n1 = System.Math.Min(_buf.ReadSize(), _buf.Size);_e0 = new System.Collections.Generic.List<int>(n1);for(var i1 = 0 ; i1 < n1 ; i1++) { int _e1;  _e1 = _buf.ReadInt(); _e0.Add(_e1);}} UpCondition.Add(_e0);}}
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);UpCost = new System.Collections.Generic.List<System.Collections.Generic.List<int>>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { System.Collections.Generic.List<int> _e0;  {int n1 = System.Math.Min(_buf.ReadSize(), _buf.Size);_e0 = new System.Collections.Generic.List<int>(n1);for(var i1 = 0 ; i1 < n1 ; i1++) { int _e1;  _e1 = _buf.ReadInt(); _e0.Add(_e1);}} UpCost.Add(_e0);}}
        BuildTime = _buf.ReadInt();
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);StarterShape = new System.Collections.Generic.List<System.Collections.Generic.List<int>>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { System.Collections.Generic.List<int> _e0;  {int n1 = System.Math.Min(_buf.ReadSize(), _buf.Size);_e0 = new System.Collections.Generic.List<int>(n1);for(var i1 = 0 ; i1 < n1 ; i1++) { int _e1;  _e1 = _buf.ReadInt(); _e0.Add(_e1);}} StarterShape.Add(_e0);}}
        Storable = _buf.ReadBool();
        Attraction = _buf.ReadInt();
        RefPrice = _buf.ReadInt();
    }

    public static BuildingLevel DeserializeBuildingLevel(ByteBuf _buf)
    {
        return new BuildingLevel(_buf);
    }

    /// <summary>
    /// 地块id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 建筑名字
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 建筑信息
    /// </summary>
    public readonly string BuildMsg;
    /// <summary>
    /// 建筑等级
    /// </summary>
    public readonly int BuildLevel;
    /// <summary>
    /// 建筑大类
    /// </summary>
    public readonly zsEnum.BuildingType BuildingType;
    /// <summary>
    /// 建筑小类
    /// </summary>
    public readonly zsEnum.BuildingSubtype BuildingSubtype;
    /// <summary>
    /// 建筑标签
    /// </summary>
    public readonly System.Collections.Generic.List<zsEnum.PreferenceTag> BuildingTag;
    /// <summary>
    /// 繁荣度
    /// </summary>
    public readonly int Prosperity;
    /// <summary>
    /// 耗电量
    /// </summary>
    public readonly int PowerConsumption;
    /// <summary>
    /// 岛屿亲和
    /// </summary>
    public readonly System.Collections.Generic.List<zsEnum.IslandType> IslandAffinity;
    /// <summary>
    /// 岗位数量
    /// </summary>
    public readonly int JobSlots;
    /// <summary>
    /// 需求职业
    /// </summary>
    public readonly zsEnum.Profession DemandOccupation;
    /// <summary>
    /// 游客承载数量
    /// </summary>
    public readonly int VisitorCapacity;
    /// <summary>
    /// 停留时间
    /// </summary>
    public readonly int DwellTime;
    /// <summary>
    /// 产出
    /// </summary>
    public readonly System.Collections.Generic.List<System.Collections.Generic.List<int>> OutPut;
    /// <summary>
    /// 产出消耗
    /// </summary>
    public readonly System.Collections.Generic.List<System.Collections.Generic.List<int>> ItemCost;
    /// <summary>
    /// 产出储存量
    /// </summary>
    public readonly System.Collections.Generic.List<System.Collections.Generic.List<int>> OutputStorage;
    /// <summary>
    /// 产出周期
    /// </summary>
    public readonly int OutputCycle;
    /// <summary>
    /// 建筑外观
    /// </summary>
    public readonly string IconId;
    /// <summary>
    /// 图片锚点
    /// </summary>
    public readonly System.Collections.Generic.List<float> Anchor;
    /// <summary>
    /// 3D模型资源
    /// </summary>
    public readonly string Model;
    /// <summary>
    /// 模型朝向
    /// </summary>
    public readonly zsEnum.Orientation Orientation;
    /// <summary>
    /// 升级条件
    /// </summary>
    public readonly System.Collections.Generic.List<System.Collections.Generic.List<int>> UpCondition;
    /// <summary>
    /// 建造消耗
    /// </summary>
    public readonly System.Collections.Generic.List<System.Collections.Generic.List<int>> UpCost;
    /// <summary>
    /// 建造时间
    /// </summary>
    public readonly int BuildTime;
    /// <summary>
    /// 初始方向&amp;形状
    /// </summary>
    public readonly System.Collections.Generic.List<System.Collections.Generic.List<int>> StarterShape;
    /// <summary>
    /// 可否存放
    /// </summary>
    public readonly bool Storable;
    /// <summary>
    /// 基础吸引力
    /// </summary>
    public readonly int Attraction;
    /// <summary>
    /// 参考价
    /// </summary>
    public readonly int RefPrice;
   
    public const int __ID__ = 401037584;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Name:" + Name + ","
        + "BuildMsg:" + BuildMsg + ","
        + "BuildLevel:" + BuildLevel + ","
        + "BuildingType:" + BuildingType + ","
        + "BuildingSubtype:" + BuildingSubtype + ","
        + "BuildingTag:" + Luban.StringUtil.CollectionToString(BuildingTag) + ","
        + "Prosperity:" + Prosperity + ","
        + "PowerConsumption:" + PowerConsumption + ","
        + "IslandAffinity:" + Luban.StringUtil.CollectionToString(IslandAffinity) + ","
        + "JobSlots:" + JobSlots + ","
        + "DemandOccupation:" + DemandOccupation + ","
        + "VisitorCapacity:" + VisitorCapacity + ","
        + "DwellTime:" + DwellTime + ","
        + "OutPut:" + Luban.StringUtil.CollectionToString(OutPut) + ","
        + "ItemCost:" + Luban.StringUtil.CollectionToString(ItemCost) + ","
        + "OutputStorage:" + Luban.StringUtil.CollectionToString(OutputStorage) + ","
        + "OutputCycle:" + OutputCycle + ","
        + "IconId:" + IconId + ","
        + "Anchor:" + Luban.StringUtil.CollectionToString(Anchor) + ","
        + "Model:" + Model + ","
        + "Orientation:" + Orientation + ","
        + "UpCondition:" + Luban.StringUtil.CollectionToString(UpCondition) + ","
        + "UpCost:" + Luban.StringUtil.CollectionToString(UpCost) + ","
        + "BuildTime:" + BuildTime + ","
        + "StarterShape:" + Luban.StringUtil.CollectionToString(StarterShape) + ","
        + "Storable:" + Storable + ","
        + "Attraction:" + Attraction + ","
        + "RefPrice:" + RefPrice + ","
        + "}";
    }
}

}
