
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public sealed partial class Employee : Luban.BeanBase
{
    public Employee(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        EmployeeName = _buf.ReadString();
        Star = (zsEnum.Star)_buf.ReadInt();
        Profession = (zsEnum.Profession)_buf.ReadInt();
        BaseEfficiency = _buf.ReadInt();
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);HireCost = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); HireCost.Add(_e0);}}
        Weight = _buf.ReadInt();
        Quality = (zsEnum.Employeequality)_buf.ReadInt();
        Icon = _buf.ReadString();
        HourlyWage = _buf.ReadInt();
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);InitialAttr = new System.Collections.Generic.List<System.Collections.Generic.List<string>>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { System.Collections.Generic.List<string> _e0;  {int n1 = System.Math.Min(_buf.ReadSize(), _buf.Size);_e0 = new System.Collections.Generic.List<string>(n1);for(var i1 = 0 ; i1 < n1 ; i1++) { string _e1;  _e1 = _buf.ReadString(); _e0.Add(_e1);}} InitialAttr.Add(_e0);}}
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);TalentID = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); TalentID.Add(_e0);}}
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);Talent1Type = new System.Collections.Generic.List<employee.TalentType>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { employee.TalentType _e0;  _e0 = employee.TalentType.DeserializeTalentType(_buf); Talent1Type.Add(_e0);}}
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);Talent2Type = new System.Collections.Generic.List<employee.TalentType>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { employee.TalentType _e0;  _e0 = employee.TalentType.DeserializeTalentType(_buf); Talent2Type.Add(_e0);}}
    }

    public static Employee DeserializeEmployee(ByteBuf _buf)
    {
        return new Employee(_buf);
    }

    /// <summary>
    /// 员工id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 员工名
    /// </summary>
    public readonly string EmployeeName;
    /// <summary>
    /// 星级
    /// </summary>
    public readonly zsEnum.Star Star;
    /// <summary>
    /// 职业
    /// </summary>
    public readonly zsEnum.Profession Profession;
    /// <summary>
    /// 基础效率
    /// </summary>
    public readonly int BaseEfficiency;
    /// <summary>
    /// 招募费用
    /// </summary>
    public readonly System.Collections.Generic.List<int> HireCost;
    /// <summary>
    /// 权重
    /// </summary>
    public readonly int Weight;
    /// <summary>
    /// 品质
    /// </summary>
    public readonly zsEnum.Employeequality Quality;
    /// <summary>
    /// 头像
    /// </summary>
    public readonly string Icon;
    /// <summary>
    /// 时薪
    /// </summary>
    public readonly int HourlyWage;
    /// <summary>
    /// 初始属性
    /// </summary>
    public readonly System.Collections.Generic.List<System.Collections.Generic.List<string>> InitialAttr;
    /// <summary>
    /// 天赋
    /// </summary>
    public readonly System.Collections.Generic.List<int> TalentID;
    /// <summary>
    /// 天赋1
    /// </summary>
    public readonly System.Collections.Generic.List<employee.TalentType> Talent1Type;
    /// <summary>
    /// 天赋2
    /// </summary>
    public readonly System.Collections.Generic.List<employee.TalentType> Talent2Type;
   
    public const int __ID__ = 1258113742;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
        
        
        
        
        
        
        
        
        
        foreach (var _e in Talent1Type) { _e?.ResolveRef(tables); }
        foreach (var _e in Talent2Type) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "employeeName:" + EmployeeName + ","
        + "star:" + Star + ","
        + "profession:" + Profession + ","
        + "baseEfficiency:" + BaseEfficiency + ","
        + "hireCost:" + Luban.StringUtil.CollectionToString(HireCost) + ","
        + "weight:" + Weight + ","
        + "quality:" + Quality + ","
        + "Icon:" + Icon + ","
        + "HourlyWage:" + HourlyWage + ","
        + "InitialAttr:" + Luban.StringUtil.CollectionToString(InitialAttr) + ","
        + "TalentID:" + Luban.StringUtil.CollectionToString(TalentID) + ","
        + "talent1Type:" + Luban.StringUtil.CollectionToString(Talent1Type) + ","
        + "talent2Type:" + Luban.StringUtil.CollectionToString(Talent2Type) + ","
        + "}";
    }
}

}
