
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.employee
{
public sealed partial class TalentType : Luban.BeanBase
{
    public TalentType(ByteBuf _buf) 
    {
        EmployeeTalentType = (zsEnum.TalentType)_buf.ReadInt();
        Value = _buf.ReadInt();
    }

    public static TalentType DeserializeTalentType(ByteBuf _buf)
    {
        return new employee.TalentType(_buf);
    }

    public readonly zsEnum.TalentType EmployeeTalentType;
    public readonly int Value;
   
    public const int __ID__ = -1339876954;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "EmployeeTalentType:" + EmployeeTalentType + ","
        + "Value:" + Value + ","
        + "}";
    }
}

}
