
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public sealed partial class Factory_Cfg : Luban.BeanBase
{
    public Factory_Cfg(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Name = _buf.ReadString();
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);InputItem = new System.Collections.Generic.List<System.Collections.Generic.List<int>>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { System.Collections.Generic.List<int> _e0;  {int n1 = System.Math.Min(_buf.ReadSize(), _buf.Size);_e0 = new System.Collections.Generic.List<int>(n1);for(var i1 = 0 ; i1 < n1 ; i1++) { int _e1;  _e1 = _buf.ReadInt(); _e0.Add(_e1);}} InputItem.Add(_e0);}}
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);OutputItem = new System.Collections.Generic.List<System.Collections.Generic.List<int>>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { System.Collections.Generic.List<int> _e0;  {int n1 = System.Math.Min(_buf.ReadSize(), _buf.Size);_e0 = new System.Collections.Generic.List<int>(n1);for(var i1 = 0 ; i1 < n1 ; i1++) { int _e1;  _e1 = _buf.ReadInt(); _e0.Add(_e1);}} OutputItem.Add(_e0);}}
        Time = _buf.ReadInt();
        MaxReserves = _buf.ReadInt();
    }

    public static Factory_Cfg DeserializeFactory_Cfg(ByteBuf _buf)
    {
        return new Factory_Cfg(_buf);
    }

    /// <summary>
    /// 生产id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 生产名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 输入物品列表
    /// </summary>
    public readonly System.Collections.Generic.List<System.Collections.Generic.List<int>> InputItem;
    /// <summary>
    /// 输出物品列表
    /// </summary>
    public readonly System.Collections.Generic.List<System.Collections.Generic.List<int>> OutputItem;
    /// <summary>
    /// 生产时间
    /// </summary>
    public readonly int Time;
    /// <summary>
    /// 最大存量
    /// </summary>
    public readonly int MaxReserves;
   
    public const int __ID__ = 1745714031;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "inputItem:" + Luban.StringUtil.CollectionToString(InputItem) + ","
        + "outputItem:" + Luban.StringUtil.CollectionToString(OutputItem) + ","
        + "time:" + Time + ","
        + "MaxReserves:" + MaxReserves + ","
        + "}";
    }
}

}
