
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public sealed partial class GameConfig : Luban.BeanBase
{
    public GameConfig(ByteBuf _buf) 
    {
        InitialNumberIslands = _buf.ReadInt();
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);InitialIslands = new System.Collections.Generic.List<System.Collections.Generic.List<int>>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { System.Collections.Generic.List<int> _e0;  {int n1 = System.Math.Min(_buf.ReadSize(), _buf.Size);_e0 = new System.Collections.Generic.List<int>(n1);for(var i1 = 0 ; i1 < n1 ; i1++) { int _e1;  _e1 = _buf.ReadInt(); _e0.Add(_e1);}} InitialIslands.Add(_e0);}}
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);InitialBuilding = new System.Collections.Generic.List<System.Collections.Generic.List<int>>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { System.Collections.Generic.List<int> _e0;  {int n1 = System.Math.Min(_buf.ReadSize(), _buf.Size);_e0 = new System.Collections.Generic.List<int>(n1);for(var i1 = 0 ; i1 < n1 ; i1++) { int _e1;  _e1 = _buf.ReadInt(); _e0.Add(_e1);}} InitialBuilding.Add(_e0);}}
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);InitialResources = new System.Collections.Generic.List<System.Collections.Generic.List<int>>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { System.Collections.Generic.List<int> _e0;  {int n1 = System.Math.Min(_buf.ReadSize(), _buf.Size);_e0 = new System.Collections.Generic.List<int>(n1);for(var i1 = 0 ; i1 < n1 ; i1++) { int _e1;  _e1 = _buf.ReadInt(); _e0.Add(_e1);}} InitialResources.Add(_e0);}}
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);IslandConstructionCosts = new System.Collections.Generic.List<System.Collections.Generic.List<int>>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { System.Collections.Generic.List<int> _e0;  {int n1 = System.Math.Min(_buf.ReadSize(), _buf.Size);_e0 = new System.Collections.Generic.List<int>(n1);for(var i1 = 0 ; i1 < n1 ; i1++) { int _e1;  _e1 = _buf.ReadInt(); _e0.Add(_e1);}} IslandConstructionCosts.Add(_e0);}}
        IslandBuildTime = _buf.ReadInt();
        ConsumptionCoefficient = _buf.ReadInt();
        TimeCoefficient = _buf.ReadInt();
        IslandConstructionVideosLimit = _buf.ReadInt();
        IslandVideoSpeedUpTime = _buf.ReadInt();
        IslandDemolitionReturn = _buf.ReadInt();
        DemolitionCooling = _buf.ReadInt();
        Prosperity = _buf.ReadInt();
        BuildWatchLimit = _buf.ReadInt();
        BuildWatchSpeedTime = _buf.ReadInt();
        IslandDemolitionTime = _buf.ReadInt();
        MainAffinityBonus = _buf.ReadInt();
        SubAffinityBonus = _buf.ReadInt();
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);InitialStarlevelDropRate = new System.Collections.Generic.List<System.Collections.Generic.List<int>>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { System.Collections.Generic.List<int> _e0;  {int n1 = System.Math.Min(_buf.ReadSize(), _buf.Size);_e0 = new System.Collections.Generic.List<int>(n1);for(var i1 = 0 ; i1 < n1 ; i1++) { int _e1;  _e1 = _buf.ReadInt(); _e0.Add(_e1);}} InitialStarlevelDropRate.Add(_e0);}}
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);BuildingLevelUpgrade = new System.Collections.Generic.List<System.Collections.Generic.List<int>>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { System.Collections.Generic.List<int> _e0;  {int n1 = System.Math.Min(_buf.ReadSize(), _buf.Size);_e0 = new System.Collections.Generic.List<int>(n1);for(var i1 = 0 ; i1 < n1 ; i1++) { int _e1;  _e1 = _buf.ReadInt(); _e0.Add(_e1);}} BuildingLevelUpgrade.Add(_e0);}}
        RecruitFreeRefreshTimes = _buf.ReadInt();
        RecruitmentRefreshResetTime = _buf.ReadInt();
        RecruitmentAutoRefreshDuration = _buf.ReadInt();
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);RecruitmentPaidRefreshInitialCost = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); RecruitmentPaidRefreshInitialCost.Add(_e0);}}
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);PaidRefreshIncreasesConsumption = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); PaidRefreshIncreasesConsumption.Add(_e0);}}
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);PaidRefreshConsumptionLimit = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); PaidRefreshConsumptionLimit.Add(_e0);}}
        InitialNumberEmployees = _buf.ReadInt();
        NumberUpgradesLevel = _buf.ReadInt();
        InitialBackpackCapacity = _buf.ReadInt();
        QuantityAddedEachTime = _buf.ReadInt();
        BackpackCapacityLimit = _buf.ReadInt();
        AirHeight = _buf.ReadInt();
        QueueTimeoutPenalty = _buf.ReadInt();
        PenaltiesFailedConsumption = _buf.ReadInt();
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);AirshipFuelDiamondReplenishment = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); AirshipFuelDiamondReplenishment.Add(_e0);}}
        AirshipTouristWelcomeTime = _buf.ReadInt();
        AirshipTouristReturnTime = _buf.ReadInt();
        AirshipTouristTimeAccelerate = _buf.ReadInt();
        AirshipTouristPassengerTransportParam = _buf.ReadInt();
        TouristGroupRefreshTime = _buf.ReadInt();
        TouristGroupRefreshGold = _buf.ReadInt();
        TouristGrouGoldpRefreshNumber = _buf.ReadInt();
        TouristGroupRefreshDiamond = _buf.ReadInt();
        GratuitySatisfactionProbability = _buf.ReadInt();
        GratuitySatisfactionGoldPercentage = _buf.ReadInt();
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);TouristQueuelimit = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); TouristQueuelimit.Add(_e0);}}
        TouristBossRefreshProbability = _buf.ReadInt();
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);BossPoorRatingBuffParameter = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); BossPoorRatingBuffParameter.Add(_e0);}}
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);BossGoldRewardParameter = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); BossGoldRewardParameter.Add(_e0);}}
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);BossLikeBuffParameter = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); BossLikeBuffParameter.Add(_e0);}}
        TouristInitialSatisfaction = _buf.ReadInt();
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);BossAngerParameter = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); BossAngerParameter.Add(_e0);}}
        EmployeeProductionAttrParameter = _buf.ReadFloat();
        EmployeeReceptionAttrParameter = _buf.ReadFloat();
        EmployeeReceptionAttrTouristParameter = _buf.ReadFloat();
        EmployeeFreeRecruitmentTime = _buf.ReadInt();
        EmployeeRecruitmentDiamondNumber = _buf.ReadInt();
        EmployeeGoldCollarRecruitmentParameter = _buf.ReadInt();
    }

    public static GameConfig DeserializeGameConfig(ByteBuf _buf)
    {
        return new GameConfig(_buf);
    }

    /// <summary>
    /// 初始岛屿数量
    /// </summary>
    public readonly int InitialNumberIslands;
    /// <summary>
    /// 初始岛屿(含位置）
    /// </summary>
    public readonly System.Collections.Generic.List<System.Collections.Generic.List<int>> InitialIslands;
    /// <summary>
    /// 初始建筑
    /// </summary>
    public readonly System.Collections.Generic.List<System.Collections.Generic.List<int>> InitialBuilding;
    /// <summary>
    /// 初始资源
    /// </summary>
    public readonly System.Collections.Generic.List<System.Collections.Generic.List<int>> InitialResources;
    /// <summary>
    /// 第一个岛屿建造消耗
    /// </summary>
    public readonly System.Collections.Generic.List<System.Collections.Generic.List<int>> IslandConstructionCosts;
    /// <summary>
    /// 第一个岛屿建造时间(s)
    /// </summary>
    public readonly int IslandBuildTime;
    /// <summary>
    /// 岛屿建造消耗系数（乘值）
    /// </summary>
    public readonly int ConsumptionCoefficient;
    /// <summary>
    /// 岛屿建造时间系数（加值）
    /// </summary>
    public readonly int TimeCoefficient;
    /// <summary>
    /// 岛屿建造观看视频次数上限
    /// </summary>
    public readonly int IslandConstructionVideosLimit;
    /// <summary>
    /// 岛屿建设视频加速时间（S）
    /// </summary>
    public readonly int IslandVideoSpeedUpTime;
    /// <summary>
    /// 岛屿拆毁返还比例（万分比）
    /// </summary>
    public readonly int IslandDemolitionReturn;
    /// <summary>
    /// 拆毁冷却时间(S)
    /// </summary>
    public readonly int DemolitionCooling;
    /// <summary>
    /// 繁荣度
    /// </summary>
    public readonly int Prosperity;
    /// <summary>
    /// 建筑观看视频上限
    /// </summary>
    public readonly int BuildWatchLimit;
    /// <summary>
    /// 建筑观看视频加速时间(s)
    /// </summary>
    public readonly int BuildWatchSpeedTime;
    /// <summary>
    /// 岛屿拆除时间比例（同建造时间比,万分比）
    /// </summary>
    public readonly int IslandDemolitionTime;
    /// <summary>
    /// 建筑主亲和加成（万分比）
    /// </summary>
    public readonly int MainAffinityBonus;
    /// <summary>
    /// 建筑副亲和加成（万分比）
    /// </summary>
    public readonly int SubAffinityBonus;
    /// <summary>
    /// 星级初始掉落率（万分比）
    /// </summary>
    public readonly System.Collections.Generic.List<System.Collections.Generic.List<int>> InitialStarlevelDropRate;
    /// <summary>
    /// 掉落率建筑等级提升值（万分比）
    /// </summary>
    public readonly System.Collections.Generic.List<System.Collections.Generic.List<int>> BuildingLevelUpgrade;
    /// <summary>
    /// 招募免费刷新次数
    /// </summary>
    public readonly int RecruitFreeRefreshTimes;
    /// <summary>
    /// 招募刷新重置时间（24小时制）
    /// </summary>
    public readonly int RecruitmentRefreshResetTime;
    /// <summary>
    /// 招募自动刷新时长
    /// </summary>
    public readonly int RecruitmentAutoRefreshDuration;
    /// <summary>
    /// 招募付费刷新初始消耗
    /// </summary>
    public readonly System.Collections.Generic.List<int> RecruitmentPaidRefreshInitialCost;
    /// <summary>
    /// 付费刷新消耗递增值（固定）
    /// </summary>
    public readonly System.Collections.Generic.List<int> PaidRefreshIncreasesConsumption;
    /// <summary>
    /// 付费刷新消耗上限
    /// </summary>
    public readonly System.Collections.Generic.List<int> PaidRefreshConsumptionLimit;
    /// <summary>
    /// 初始员工人数
    /// </summary>
    public readonly int InitialNumberEmployees;
    /// <summary>
    /// 每级提升人数
    /// </summary>
    public readonly int NumberUpgradesLevel;
    /// <summary>
    /// 背包初始容量
    /// </summary>
    public readonly int InitialBackpackCapacity;
    /// <summary>
    /// 每次扩容数量
    /// </summary>
    public readonly int QuantityAddedEachTime;
    /// <summary>
    /// 背包容量上限
    /// </summary>
    public readonly int BackpackCapacityLimit;
    /// <summary>
    /// 垂直高度差
    /// </summary>
    public readonly int AirHeight;
    /// <summary>
    /// 排队失败惩罚(扣满意度）
    /// </summary>
    public readonly int QueueTimeoutPenalty;
    /// <summary>
    /// 消费失败惩罚(扣满意度）
    /// </summary>
    public readonly int PenaltiesFailedConsumption;
    /// <summary>
    /// 飞艇燃油不足补充--(消耗的钻石;补充的燃油数量)
    /// </summary>
    public readonly System.Collections.Generic.List<int> AirshipFuelDiamondReplenishment;
    /// <summary>
    /// 飞艇接客需要的时间-前期接客队列-秒（S）
    /// </summary>
    public readonly int AirshipTouristWelcomeTime;
    /// <summary>
    /// 飞艇返回需要的时间-接客返回队列-秒（S）
    /// </summary>
    public readonly int AirshipTouristReturnTime;
    /// <summary>
    /// 飞艇加速的时间(百分比)
    /// </summary>
    public readonly int AirshipTouristTimeAccelerate;
    /// <summary>
    /// 飞艇载客数量
    /// </summary>
    public readonly int AirshipTouristPassengerTransportParam;
    /// <summary>
    /// 游客团免费刷新时间间隔-秒（S）
    /// </summary>
    public readonly int TouristGroupRefreshTime;
    /// <summary>
    /// 游客团刷新金币消耗
    /// </summary>
    public readonly int TouristGroupRefreshGold;
    /// <summary>
    /// 游客团金币刷新次数
    /// </summary>
    public readonly int TouristGrouGoldpRefreshNumber;
    /// <summary>
    /// 游客团刷新钻石消耗
    /// </summary>
    public readonly int TouristGroupRefreshDiamond;
    /// <summary>
    /// 小费满意度概率(百分比)
    /// </summary>
    public readonly int GratuitySatisfactionProbability;
    /// <summary>
    /// 小费金币比例(百分比)
    /// </summary>
    public readonly int GratuitySatisfactionGoldPercentage;
    /// <summary>
    /// 游客排队上限(按岛屿大小分为3种类型)
    /// </summary>
    public readonly System.Collections.Generic.List<int> TouristQueuelimit;
    /// <summary>
    /// Boss的刷新概率
    /// </summary>
    public readonly int TouristBossRefreshProbability;
    /// <summary>
    /// “差评”状态参数。（持续时间-秒;游客滞留时间增加-百分比）
    /// </summary>
    public readonly System.Collections.Generic.List<int> BossPoorRatingBuffParameter;
    /// <summary>
    /// Boss金币奖励参数-百分比(暴怒安抚成功;撒钱)
    /// </summary>
    public readonly System.Collections.Generic.List<int> BossGoldRewardParameter;
    /// <summary>
    /// “点赞”状态参数。（持续时间-秒;游客滞留时间降低-百分比）
    /// </summary>
    public readonly System.Collections.Generic.List<int> BossLikeBuffParameter;
    /// <summary>
    /// 生成时的初始满意度
    /// </summary>
    public readonly int TouristInitialSatisfaction;
    /// <summary>
    /// BOSS“暴怒”状态小游戏参数--(持续时间|点击次数)
    /// </summary>
    public readonly System.Collections.Generic.List<int> BossAngerParameter;
    /// <summary>
    /// 员工生成能力属性点参数-百分比
    /// </summary>
    public readonly float EmployeeProductionAttrParameter;
    /// <summary>
    /// 员工接待能力属性点参数-百分比
    /// </summary>
    public readonly float EmployeeReceptionAttrParameter;
    /// <summary>
    /// 接待能力游客上限影响参数
    /// </summary>
    public readonly float EmployeeReceptionAttrTouristParameter;
    /// <summary>
    /// 员工招募免费刷新倒计时-秒
    /// </summary>
    public readonly int EmployeeFreeRecruitmentTime;
    /// <summary>
    /// 员工招募需要的钻石数量
    /// </summary>
    public readonly int EmployeeRecruitmentDiamondNumber;
    /// <summary>
    /// 金领员工保底次数
    /// </summary>
    public readonly int EmployeeGoldCollarRecruitmentParameter;
   
    public const int __ID__ = -2136581644;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "InitialNumberIslands:" + InitialNumberIslands + ","
        + "InitialIslands:" + Luban.StringUtil.CollectionToString(InitialIslands) + ","
        + "InitialBuilding:" + Luban.StringUtil.CollectionToString(InitialBuilding) + ","
        + "InitialResources:" + Luban.StringUtil.CollectionToString(InitialResources) + ","
        + "IslandConstructionCosts:" + Luban.StringUtil.CollectionToString(IslandConstructionCosts) + ","
        + "IslandBuildTime:" + IslandBuildTime + ","
        + "ConsumptionCoefficient:" + ConsumptionCoefficient + ","
        + "TimeCoefficient:" + TimeCoefficient + ","
        + "IslandConstructionVideosLimit:" + IslandConstructionVideosLimit + ","
        + "IslandVideoSpeedUpTime:" + IslandVideoSpeedUpTime + ","
        + "IslandDemolitionReturn:" + IslandDemolitionReturn + ","
        + "DemolitionCooling:" + DemolitionCooling + ","
        + "Prosperity:" + Prosperity + ","
        + "BuildWatchLimit:" + BuildWatchLimit + ","
        + "BuildWatchSpeedTime:" + BuildWatchSpeedTime + ","
        + "IslandDemolitionTime:" + IslandDemolitionTime + ","
        + "MainAffinityBonus:" + MainAffinityBonus + ","
        + "SubAffinityBonus:" + SubAffinityBonus + ","
        + "InitialStarlevelDropRate:" + Luban.StringUtil.CollectionToString(InitialStarlevelDropRate) + ","
        + "BuildingLevelUpgrade:" + Luban.StringUtil.CollectionToString(BuildingLevelUpgrade) + ","
        + "RecruitFreeRefreshTimes:" + RecruitFreeRefreshTimes + ","
        + "RecruitmentRefreshResetTime:" + RecruitmentRefreshResetTime + ","
        + "RecruitmentAutoRefreshDuration:" + RecruitmentAutoRefreshDuration + ","
        + "RecruitmentPaidRefreshInitialCost:" + Luban.StringUtil.CollectionToString(RecruitmentPaidRefreshInitialCost) + ","
        + "PaidRefreshIncreasesConsumption:" + Luban.StringUtil.CollectionToString(PaidRefreshIncreasesConsumption) + ","
        + "PaidRefreshConsumptionLimit:" + Luban.StringUtil.CollectionToString(PaidRefreshConsumptionLimit) + ","
        + "InitialNumberEmployees:" + InitialNumberEmployees + ","
        + "NumberUpgradesLevel:" + NumberUpgradesLevel + ","
        + "InitialBackpackCapacity:" + InitialBackpackCapacity + ","
        + "QuantityAddedEachTime:" + QuantityAddedEachTime + ","
        + "BackpackCapacityLimit:" + BackpackCapacityLimit + ","
        + "airHeight:" + AirHeight + ","
        + "QueueTimeoutPenalty:" + QueueTimeoutPenalty + ","
        + "PenaltiesFailedConsumption:" + PenaltiesFailedConsumption + ","
        + "AirshipFuelDiamondReplenishment:" + Luban.StringUtil.CollectionToString(AirshipFuelDiamondReplenishment) + ","
        + "AirshipTouristWelcomeTime:" + AirshipTouristWelcomeTime + ","
        + "AirshipTouristReturnTime:" + AirshipTouristReturnTime + ","
        + "AirshipTouristTimeAccelerate:" + AirshipTouristTimeAccelerate + ","
        + "AirshipTouristPassengerTransportParam:" + AirshipTouristPassengerTransportParam + ","
        + "TouristGroupRefreshTime:" + TouristGroupRefreshTime + ","
        + "TouristGroupRefreshGold:" + TouristGroupRefreshGold + ","
        + "TouristGrouGoldpRefreshNumber:" + TouristGrouGoldpRefreshNumber + ","
        + "TouristGroupRefreshDiamond:" + TouristGroupRefreshDiamond + ","
        + "GratuitySatisfactionProbability:" + GratuitySatisfactionProbability + ","
        + "GratuitySatisfactionGoldPercentage:" + GratuitySatisfactionGoldPercentage + ","
        + "TouristQueuelimit:" + Luban.StringUtil.CollectionToString(TouristQueuelimit) + ","
        + "TouristBossRefreshProbability:" + TouristBossRefreshProbability + ","
        + "BossPoorRatingBuffParameter:" + Luban.StringUtil.CollectionToString(BossPoorRatingBuffParameter) + ","
        + "BossGoldRewardParameter:" + Luban.StringUtil.CollectionToString(BossGoldRewardParameter) + ","
        + "BossLikeBuffParameter:" + Luban.StringUtil.CollectionToString(BossLikeBuffParameter) + ","
        + "TouristInitialSatisfaction:" + TouristInitialSatisfaction + ","
        + "BossAngerParameter:" + Luban.StringUtil.CollectionToString(BossAngerParameter) + ","
        + "EmployeeProductionAttrParameter:" + EmployeeProductionAttrParameter + ","
        + "EmployeeReceptionAttrParameter:" + EmployeeReceptionAttrParameter + ","
        + "EmployeeReceptionAttrTouristParameter:" + EmployeeReceptionAttrTouristParameter + ","
        + "EmployeeFreeRecruitmentTime:" + EmployeeFreeRecruitmentTime + ","
        + "EmployeeRecruitmentDiamondNumber:" + EmployeeRecruitmentDiamondNumber + ","
        + "EmployeeGoldCollarRecruitmentParameter:" + EmployeeGoldCollarRecruitmentParameter + ","
        + "}";
    }
}

}
