
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public sealed partial class GuideStep : Luban.BeanBase
{
    public GuideStep(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        GroupId = _buf.ReadInt();
        NextId = _buf.ReadInt();
        MaskPadding = ExternalTypeUtil.NewVector2(vector2.Deserializevector2(_buf));
        MaskType = (GuideMaskType)_buf.ReadInt();
        ShowHand = _buf.ReadBool();
        HandOffset = ExternalTypeUtil.NewVector2(vector2.Deserializevector2(_buf));
        ForceGuide = _buf.ReadBool();
        UiPath = _buf.ReadString();
        ContentText = _buf.ReadString();
    }

    public static GuideStep DeserializeGuideStep(ByteBuf _buf)
    {
        return new GuideStep(_buf);
    }

    /// <summary>
    /// 步骤唯一ID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 引导组ID(用于触发整套引导)
    /// </summary>
    public readonly int GroupId;
    /// <summary>
    /// 下一步ID (0表示结束)
    /// </summary>
    public readonly int NextId;
    /// <summary>
    /// 遮罩额外边距(x,y)
    /// </summary>
    public readonly UnityEngine.Vector2 MaskPadding;
    /// <summary>
    /// 遮罩类型
    /// </summary>
    public readonly GuideMaskType MaskType;
    /// <summary>
    /// 是否显示手指提示
    /// </summary>
    public readonly bool ShowHand;
    /// <summary>
    /// 手指相对目标的偏移
    /// </summary>
    public readonly UnityEngine.Vector2 HandOffset;
    /// <summary>
    /// 强引导(点击遮罩外无效)
    /// </summary>
    public readonly bool ForceGuide;
    /// <summary>
    /// 目标UI在Canvas下的路径
    /// </summary>
    public readonly string UiPath;
    /// <summary>
    /// 引导对话框文本
    /// </summary>
    public readonly string ContentText;
   
    public const int __ID__ = -72484920;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
        
        
        
        
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "groupId:" + GroupId + ","
        + "nextId:" + NextId + ","
        + "maskPadding:" + MaskPadding + ","
        + "maskType:" + MaskType + ","
        + "showHand:" + ShowHand + ","
        + "handOffset:" + HandOffset + ","
        + "forceGuide:" + ForceGuide + ","
        + "uiPath:" + UiPath + ","
        + "contentText:" + ContentText + ","
        + "}";
    }
}

}
