
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public sealed partial class IslandLevel : Luban.BeanBase
{
    public IslandLevel(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        IslandName = _buf.ReadString();
        IslandType = (zsEnum.IslandType)_buf.ReadInt();
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);BuildableStructures = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); BuildableStructures.Add(_e0);}}
        BonusBuildingTypes = (zsEnum.IslandBonusType)_buf.ReadInt();
        Value = _buf.ReadInt();
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);UpgradeCost = new System.Collections.Generic.List<System.Collections.Generic.List<int>>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { System.Collections.Generic.List<int> _e0;  {int n1 = System.Math.Min(_buf.ReadSize(), _buf.Size);_e0 = new System.Collections.Generic.List<int>(n1);for(var i1 = 0 ; i1 < n1 ; i1++) { int _e1;  _e1 = _buf.ReadInt(); _e0.Add(_e1);}} UpgradeCost.Add(_e0);}}
        UpgradeTime = _buf.ReadInt();
        TypeIcon = _buf.ReadString();
        SurfaceModel = _buf.ReadString();
        Image = _buf.ReadString();
    }

    public static IslandLevel DeserializeIslandLevel(ByteBuf _buf)
    {
        return new IslandLevel(_buf);
    }

    /// <summary>
    /// 岛屿id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 岛屿名称
    /// </summary>
    public readonly string IslandName;
    /// <summary>
    /// 岛屿类型
    /// </summary>
    public readonly zsEnum.IslandType IslandType;
    /// <summary>
    /// 可建建筑（建筑小类）
    /// </summary>
    public readonly System.Collections.Generic.List<int> BuildableStructures;
    /// <summary>
    /// 加成建筑类型
    /// </summary>
    public readonly zsEnum.IslandBonusType BonusBuildingTypes;
    /// <summary>
    /// 加成值(万分比）
    /// </summary>
    public readonly int Value;
    /// <summary>
    /// 升级消耗（道具id;数量|道具id…）
    /// </summary>
    public readonly System.Collections.Generic.List<System.Collections.Generic.List<int>> UpgradeCost;
    /// <summary>
    /// 升级时间（S）
    /// </summary>
    public readonly int UpgradeTime;
    /// <summary>
    /// 类型图标
    /// </summary>
    public readonly string TypeIcon;
    /// <summary>
    /// 地表模型
    /// </summary>
    public readonly string SurfaceModel;
    /// <summary>
    /// 地块形象
    /// </summary>
    public readonly string Image;
   
    public const int __ID__ = -2057937329;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
        
        
        
        
        
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "IslandName:" + IslandName + ","
        + "IslandType:" + IslandType + ","
        + "BuildableStructures:" + Luban.StringUtil.CollectionToString(BuildableStructures) + ","
        + "BonusBuildingTypes:" + BonusBuildingTypes + ","
        + "Value:" + Value + ","
        + "UpgradeCost:" + Luban.StringUtil.CollectionToString(UpgradeCost) + ","
        + "UpgradeTime:" + UpgradeTime + ","
        + "TypeIcon:" + TypeIcon + ","
        + "SurfaceModel:" + SurfaceModel + ","
        + "Image:" + Image + ","
        + "}";
    }
}

}
