
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public sealed partial class Island_Config : Luban.BeanBase
{
    public Island_Config(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Name = _buf.ReadString();
        ResourceName = _buf.ReadString();
        Length = _buf.ReadInt();
        Width = _buf.ReadInt();
        Height = _buf.ReadInt();
        AirHeight = _buf.ReadInt();
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);BuildArea = new System.Collections.Generic.List<System.Collections.Generic.List<int>>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { System.Collections.Generic.List<int> _e0;  {int n1 = System.Math.Min(_buf.ReadSize(), _buf.Size);_e0 = new System.Collections.Generic.List<int>(n1);for(var i1 = 0 ; i1 < n1 ; i1++) { int _e1;  _e1 = _buf.ReadInt(); _e0.Add(_e1);}} BuildArea.Add(_e0);}}
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);AttachmentPoint = new System.Collections.Generic.List<System.Collections.Generic.List<int>>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { System.Collections.Generic.List<int> _e0;  {int n1 = System.Math.Min(_buf.ReadSize(), _buf.Size);_e0 = new System.Collections.Generic.List<int>(n1);for(var i1 = 0 ; i1 < n1 ; i1++) { int _e1;  _e1 = _buf.ReadInt(); _e0.Add(_e1);}} AttachmentPoint.Add(_e0);}}
    }

    public static Island_Config DeserializeIsland_Config(ByteBuf _buf)
    {
        return new Island_Config(_buf);
    }

    /// <summary>
    /// 岛屿id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 岛屿名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 岛屿资源名
    /// </summary>
    public readonly string ResourceName;
    /// <summary>
    /// 长度
    /// </summary>
    public readonly int Length;
    /// <summary>
    /// 宽度
    /// </summary>
    public readonly int Width;
    /// <summary>
    /// 高度
    /// </summary>
    public readonly int Height;
    /// <summary>
    /// 空域高度
    /// </summary>
    public readonly int AirHeight;
    /// <summary>
    /// 可建筑范围
    /// </summary>
    public readonly System.Collections.Generic.List<System.Collections.Generic.List<int>> BuildArea;
    /// <summary>
    /// 附着点
    /// </summary>
    public readonly System.Collections.Generic.List<System.Collections.Generic.List<int>> AttachmentPoint;
   
    public const int __ID__ = 1005260972;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
        
        
        
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "resourceName:" + ResourceName + ","
        + "length:" + Length + ","
        + "width:" + Width + ","
        + "height:" + Height + ","
        + "airHeight:" + AirHeight + ","
        + "buildArea:" + Luban.StringUtil.CollectionToString(BuildArea) + ","
        + "attachmentPoint:" + Luban.StringUtil.CollectionToString(AttachmentPoint) + ","
        + "}";
    }
}

}
