
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public sealed partial class Item : Luban.BeanBase
{
    public Item(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Name = _buf.ReadString();
        Desc = _buf.ReadString();
        Colour = _buf.ReadInt();
        Type = (zsEnum.ItemType)_buf.ReadInt();
        IsHide = _buf.ReadBool();
        MaxLimit = _buf.ReadLong();
        HasMax = _buf.ReadInt();
        UseType = _buf.ReadInt();
        UseMax = _buf.ReadLong();
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);Effect = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); Effect.Add(_e0);}}
        JumpId = _buf.ReadString();
        Icon = _buf.ReadString();
    }

    public static Item DeserializeItem(ByteBuf _buf)
    {
        return new Item(_buf);
    }

    /// <summary>
    /// 物品id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 物品描述
    /// </summary>
    public readonly string Desc;
    /// <summary>
    /// 品质
    /// </summary>
    public readonly int Colour;
    /// <summary>
    /// 类型
    /// </summary>
    public readonly zsEnum.ItemType Type;
    /// <summary>
    /// 是否背包显示
    /// </summary>
    public readonly bool IsHide;
    /// <summary>
    /// 单组数量
    /// </summary>
    public readonly long MaxLimit;
    /// <summary>
    /// 拥有上限
    /// </summary>
    public readonly int HasMax;
    /// <summary>
    /// 使用类型
    /// </summary>
    public readonly int UseType;
    /// <summary>
    /// 使用最大数量
    /// </summary>
    public readonly long UseMax;
    /// <summary>
    /// 道具效果
    /// </summary>
    public readonly System.Collections.Generic.List<int> Effect;
    /// <summary>
    /// 使用跳转
    /// </summary>
    public readonly string JumpId;
    /// <summary>
    /// 图标资源
    /// </summary>
    public readonly string Icon;
   
    public const int __ID__ = 2289459;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
        
        
        
        
        
        
        
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "desc:" + Desc + ","
        + "colour:" + Colour + ","
        + "type:" + Type + ","
        + "IsHide:" + IsHide + ","
        + "maxLimit:" + MaxLimit + ","
        + "hasMax:" + HasMax + ","
        + "useType:" + UseType + ","
        + "useMax:" + UseMax + ","
        + "Effect:" + Luban.StringUtil.CollectionToString(Effect) + ","
        + "jumpId:" + JumpId + ","
        + "icon:" + Icon + ","
        + "}";
    }
}

}
