
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public partial class ItemCfg
{
    private readonly System.Collections.Generic.Dictionary<int, Item_Cfg> _dataMap;
    private readonly System.Collections.Generic.List<Item_Cfg> _dataList;
    
    public ItemCfg(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Item_Cfg>();
        _dataList = new System.Collections.Generic.List<Item_Cfg>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            Item_Cfg _v;
            _v = Item_Cfg.DeserializeItem_Cfg(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Item_Cfg> DataMap => _dataMap;
    public System.Collections.Generic.List<Item_Cfg> DataList => _dataList;

    public Item_Cfg GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Item_Cfg Get(int key) => _dataMap[key];
    public Item_Cfg this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

