
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public sealed partial class Item_Cfg : Luban.BeanBase
{
    public Item_Cfg(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Name = _buf.ReadString();
        Description = _buf.ReadString();
        Icon = _buf.ReadString();
        ItemType = (item.ItemType)_buf.ReadInt();
        ItemQuality = (item.ItemQuality)_buf.ReadInt();
    }

    public static Item_Cfg DeserializeItem_Cfg(ByteBuf _buf)
    {
        return new Item_Cfg(_buf);
    }

    /// <summary>
    /// 物品id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 物品名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 物品描述
    /// </summary>
    public readonly string Description;
    /// <summary>
    /// 物品图标
    /// </summary>
    public readonly string Icon;
    /// <summary>
    /// 物品类型
    /// </summary>
    public readonly item.ItemType ItemType;
    /// <summary>
    /// 物品品质
    /// </summary>
    public readonly item.ItemQuality ItemQuality;
   
    public const int __ID__ = 1242453304;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "Description:" + Description + ","
        + "icon:" + Icon + ","
        + "ItemType:" + ItemType + ","
        + "ItemQuality:" + ItemQuality + ","
        + "}";
    }
}

}
