
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg.item
{ 
    public enum ItemQuality
    {
        /// <summary>
        /// 普通
        /// </summary>
        Common = 1,
        /// <summary>
        /// 稀有
        /// </summary>
        Rare = 2,
    }

} 

