
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg.item
{ 
    public enum ItemType
    {
        /// <summary>
        /// 基础资源
        /// </summary>
        Resource = 1,
        /// <summary>
        /// 消耗品
        /// </summary>
        Consumable = 2,
    }

} 

