
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public sealed partial class MapBoundary : Luban.BeanBase
{
    public MapBoundary(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        MinX = _buf.ReadInt();
        MinY = _buf.ReadInt();
        MaxX = _buf.ReadInt();
        MaxY = _buf.ReadInt();
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);InitTile = new System.Collections.Generic.List<System.Collections.Generic.List<int>>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { System.Collections.Generic.List<int> _e0;  {int n1 = System.Math.Min(_buf.ReadSize(), _buf.Size);_e0 = new System.Collections.Generic.List<int>(n1);for(var i1 = 0 ; i1 < n1 ; i1++) { int _e1;  _e1 = _buf.ReadInt(); _e0.Add(_e1);}} InitTile.Add(_e0);}}
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);Island1 = new System.Collections.Generic.List<System.Collections.Generic.List<int>>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { System.Collections.Generic.List<int> _e0;  {int n1 = System.Math.Min(_buf.ReadSize(), _buf.Size);_e0 = new System.Collections.Generic.List<int>(n1);for(var i1 = 0 ; i1 < n1 ; i1++) { int _e1;  _e1 = _buf.ReadInt(); _e0.Add(_e1);}} Island1.Add(_e0);}}
        StartTileid = _buf.ReadInt();
    }

    public static MapBoundary DeserializeMapBoundary(ByteBuf _buf)
    {
        return new MapBoundary(_buf);
    }

    /// <summary>
    /// 地图id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 可建造最小 X 坐标
    /// </summary>
    public readonly int MinX;
    /// <summary>
    /// 可建造最小 Y 坐标
    /// </summary>
    public readonly int MinY;
    /// <summary>
    /// 可建造最大 X 坐标
    /// </summary>
    public readonly int MaxX;
    /// <summary>
    /// 可建造最大 Y 坐标
    /// </summary>
    public readonly int MaxY;
    /// <summary>
    /// 初始地块
    /// </summary>
    public readonly System.Collections.Generic.List<System.Collections.Generic.List<int>> InitTile;
    /// <summary>
    /// 初始浮屿
    /// </summary>
    public readonly System.Collections.Generic.List<System.Collections.Generic.List<int>> Island1;
    /// <summary>
    /// 初始地块ID
    /// </summary>
    public readonly int StartTileid;
   
    public const int __ID__ = -1135379066;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
        
        
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "MinX:" + MinX + ","
        + "MinY:" + MinY + ","
        + "MaxX:" + MaxX + ","
        + "MaxY:" + MaxY + ","
        + "InitTile:" + Luban.StringUtil.CollectionToString(InitTile) + ","
        + "Island1:" + Luban.StringUtil.CollectionToString(Island1) + ","
        + "StartTileid:" + StartTileid + ","
        + "}";
    }
}

}
