
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public sealed partial class Prosperity : Luban.BeanBase
{
    public Prosperity(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Level = _buf.ReadInt();
        Prosperitys = _buf.ReadInt();
        MaxIslands = _buf.ReadInt();
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);RandomProbabilityIslands = new System.Collections.Generic.List<System.Collections.Generic.List<int>>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { System.Collections.Generic.List<int> _e0;  {int n1 = System.Math.Min(_buf.ReadSize(), _buf.Size);_e0 = new System.Collections.Generic.List<int>(n1);for(var i1 = 0 ; i1 < n1 ; i1++) { int _e1;  _e1 = _buf.ReadInt(); _e0.Add(_e1);}} RandomProbabilityIslands.Add(_e0);}}
        TouristCorrectionCoefficient = _buf.ReadInt();
    }

    public static Prosperity DeserializeProsperity(ByteBuf _buf)
    {
        return new Prosperity(_buf);
    }

    /// <summary>
    /// 编号
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 等级
    /// </summary>
    public readonly int Level;
    /// <summary>
    /// 繁荣度（达成值）
    /// </summary>
    public readonly int Prosperitys;
    /// <summary>
    /// 岛屿上限
    /// </summary>
    public readonly int MaxIslands;
    /// <summary>
    /// 岛屿随机概率(万分比）
    /// </summary>
    public readonly System.Collections.Generic.List<System.Collections.Generic.List<int>> RandomProbabilityIslands;
    /// <summary>
    /// 游客修正系数(万分比）
    /// </summary>
    public readonly int TouristCorrectionCoefficient;
   
    public const int __ID__ = -262188681;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "Level:" + Level + ","
        + "Prosperitys:" + Prosperitys + ","
        + "MaxIslands:" + MaxIslands + ","
        + "RandomProbabilityIslands:" + Luban.StringUtil.CollectionToString(RandomProbabilityIslands) + ","
        + "TouristCorrectionCoefficient:" + TouristCorrectionCoefficient + ","
        + "}";
    }
}

}
