
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;
using Cysharp.Threading.Tasks;

namespace cfg
{
public partial class Tables
{
    public Framework.ChapterCfg ChapterCfg {get; private set; }
    public IslandCfg IslandCfg {get; private set; }
    public BuildingCfg BuildingCfg {get; private set; }
    public BridgeCfg BridgeCfg {get; private set; }
    public GuideCfg GuideCfg {get; private set; }
    public ItemCfg ItemCfg {get; private set; }
    public FactoryCfg FactoryCfg {get; private set; }
    public ServiceCfg ServiceCfg {get; private set; }

    /// public Tables(System.Func<string, ByteBuf> loader)
    public Tables()
    {
        ///        /// ChapterCfg = new Framework.ChapterCfg(loader("framework_chaptercfg"));
        ///        /// IslandCfg = new IslandCfg(loader("islandcfg"));
        ///        /// BuildingCfg = new BuildingCfg(loader("buildingcfg"));
        ///        /// BridgeCfg = new BridgeCfg(loader("bridgecfg"));
        ///        /// GuideCfg = new GuideCfg(loader("guidecfg"));
        ///        /// ItemCfg = new ItemCfg(loader("itemcfg"));
        ///        /// FactoryCfg = new FactoryCfg(loader("factorycfg"));
        ///        /// ServiceCfg = new ServiceCfg(loader("servicecfg"));
        ///        /// ResolveRef();
    }

    public async UniTask LoadAsync(System.Func<string, UniTask<ByteBuf>> loader)
    {
        var tables = new System.Collections.Generic.Dictionary<string, object>();
		List<UniTask> list = new List<UniTask>();
		list.Add(UniTask.Create(async () =>
		{
			ChapterCfg = new Framework.ChapterCfg(await loader("framework_chaptercfg")); 
			tables.Add("Framework.ChapterCfg", ChapterCfg);
		}));
		list.Add(UniTask.Create(async () =>
		{
			IslandCfg = new IslandCfg(await loader("islandcfg")); 
			tables.Add("IslandCfg", IslandCfg);
		}));
		list.Add(UniTask.Create(async () =>
		{
			BuildingCfg = new BuildingCfg(await loader("buildingcfg")); 
			tables.Add("BuildingCfg", BuildingCfg);
		}));
		list.Add(UniTask.Create(async () =>
		{
			BridgeCfg = new BridgeCfg(await loader("bridgecfg")); 
			tables.Add("BridgeCfg", BridgeCfg);
		}));
		list.Add(UniTask.Create(async () =>
		{
			GuideCfg = new GuideCfg(await loader("guidecfg")); 
			tables.Add("GuideCfg", GuideCfg);
		}));
		list.Add(UniTask.Create(async () =>
		{
			ItemCfg = new ItemCfg(await loader("itemcfg")); 
			tables.Add("ItemCfg", ItemCfg);
		}));
		list.Add(UniTask.Create(async () =>
		{
			FactoryCfg = new FactoryCfg(await loader("factorycfg")); 
			tables.Add("FactoryCfg", FactoryCfg);
		}));
		list.Add(UniTask.Create(async () =>
		{
			ServiceCfg = new ServiceCfg(await loader("servicecfg")); 
			tables.Add("ServiceCfg", ServiceCfg);
		}));

		await UniTask.WhenAll(list);

        ResolveRef();
    }
    
    private void ResolveRef()
    {
        ChapterCfg.ResolveRef(this);
        IslandCfg.ResolveRef(this);
        BuildingCfg.ResolveRef(this);
        BridgeCfg.ResolveRef(this);
        GuideCfg.ResolveRef(this);
        ItemCfg.ResolveRef(this);
        FactoryCfg.ResolveRef(this);
        ServiceCfg.ResolveRef(this);
    }
}

}
