
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg.task
{ 
    public enum TaskType
    {
        /// <summary>
        /// 建造
        /// </summary>
        Build = 1,
        /// <summary>
        /// 收集
        /// </summary>
        Collect = 2,
    }

} 

