
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public sealed partial class Task : Luban.BeanBase
{
    public Task(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        QuestTitle = _buf.ReadString();
        QuestType = _buf.ReadInt();
        TriggerType = _buf.ReadInt();
        AftQuestList = _buf.ReadInt();
        Target = _buf.ReadString();
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);RewardItems = new System.Collections.Generic.List<System.Collections.Generic.List<int>>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { System.Collections.Generic.List<int> _e0;  {int n1 = System.Math.Min(_buf.ReadSize(), _buf.Size);_e0 = new System.Collections.Generic.List<int>(n1);for(var i1 = 0 ; i1 < n1 ; i1++) { int _e1;  _e1 = _buf.ReadInt(); _e0.Add(_e1);}} RewardItems.Add(_e0);}}
    }

    public static Task DeserializeTask(ByteBuf _buf)
    {
        return new Task(_buf);
    }

    /// <summary>
    /// 任务ID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 任务标题
    /// </summary>
    public readonly string QuestTitle;
    /// <summary>
    /// 任务类型
    /// </summary>
    public readonly int QuestType;
    /// <summary>
    /// 触发
    /// </summary>
    public readonly int TriggerType;
    /// <summary>
    /// 任务链
    /// </summary>
    public readonly int AftQuestList;
    /// <summary>
    /// 完成条件
    /// </summary>
    public readonly string Target;
    /// <summary>
    /// 道具奖励
    /// </summary>
    public readonly System.Collections.Generic.List<System.Collections.Generic.List<int>> RewardItems;
   
    public const int __ID__ = 2599333;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
        
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "QuestTitle:" + QuestTitle + ","
        + "QuestType:" + QuestType + ","
        + "TriggerType:" + TriggerType + ","
        + "AftQuestList:" + AftQuestList + ","
        + "Target:" + Target + ","
        + "RewardItems:" + Luban.StringUtil.CollectionToString(RewardItems) + ","
        + "}";
    }
}

}
