
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public sealed partial class Tourist : Luban.BeanBase
{
    public Tourist(ByteBuf _buf) 
    {
        ID = _buf.ReadInt();
        Gender = (zsEnum.Gender)_buf.ReadInt();
        AgeGroup = (zsEnum.AgeGroup)_buf.ReadInt();
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);InitialGold = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); InitialGold.Add(_e0);}}
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);Tags = new System.Collections.Generic.List<zsEnum.PreferenceTag>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { zsEnum.PreferenceTag _e0;  _e0 = (zsEnum.PreferenceTag)_buf.ReadInt(); Tags.Add(_e0);}}
        BaseMoveSpeed = _buf.ReadFloat();
        MaxWaitTime = _buf.ReadInt();
        MaxConsecutiveDisappointment = _buf.ReadInt();
        RefreshWeight = _buf.ReadInt();
        InitSatisfaction = _buf.ReadInt();
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);InitStayTime = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); InitStayTime.Add(_e0);}}
        MaxStayTime = _buf.ReadInt();
        PatienceDecay = _buf.ReadInt();
        SatisfactionThreshold = _buf.ReadInt();
        TimeBonus = _buf.ReadInt();
        FallbackEnabled = _buf.ReadBool();
        ModelID = _buf.ReadString();
    }

    public static Tourist DeserializeTourist(ByteBuf _buf)
    {
        return new Tourist(_buf);
    }

    /// <summary>
    /// ID
    /// </summary>
    public readonly int ID;
    /// <summary>
    /// 性别 (Enum)
    /// </summary>
    public readonly zsEnum.Gender Gender;
    /// <summary>
    /// 年龄组 (Enum)
    /// </summary>
    public readonly zsEnum.AgeGroup AgeGroup;
    /// <summary>
    /// 初始金币(范围内随机）
    /// </summary>
    public readonly System.Collections.Generic.List<int> InitialGold;
    /// <summary>
    /// 兴趣标签
    /// </summary>
    public readonly System.Collections.Generic.List<zsEnum.PreferenceTag> Tags;
    /// <summary>
    /// 基础移动速度(M/S)
    /// </summary>
    public readonly float BaseMoveSpeed;
    /// <summary>
    /// 最大排队时间 (S)
    /// </summary>
    public readonly int MaxWaitTime;
    /// <summary>
    /// 最大连续失望次数
    /// </summary>
    public readonly int MaxConsecutiveDisappointment;
    /// <summary>
    /// 刷新权重
    /// </summary>
    public readonly int RefreshWeight;
    /// <summary>
    /// 初始满意度
    /// </summary>
    public readonly int InitSatisfaction;
    /// <summary>
    /// 初始在园时间(秒)
    /// </summary>
    public readonly System.Collections.Generic.List<int> InitStayTime;
    /// <summary>
    /// 最大在园时间(S)
    /// </summary>
    public readonly int MaxStayTime;
    /// <summary>
    /// 排队耐心衰减
    /// </summary>
    public readonly int PatienceDecay;
    /// <summary>
    /// 满足奖励阈值（满意度）
    /// </summary>
    public readonly int SatisfactionThreshold;
    /// <summary>
    /// 满足奖励时长(秒)
    /// </summary>
    public readonly int TimeBonus;
    /// <summary>
    /// 允许去无标签建筑
    /// </summary>
    public readonly bool FallbackEnabled;
    /// <summary>
    /// 模型资源ID
    /// </summary>
    public readonly string ModelID;
   
    public const int __ID__ = 530286354;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "ID:" + ID + ","
        + "Gender:" + Gender + ","
        + "AgeGroup:" + AgeGroup + ","
        + "InitialGold:" + Luban.StringUtil.CollectionToString(InitialGold) + ","
        + "Tags:" + Luban.StringUtil.CollectionToString(Tags) + ","
        + "BaseMoveSpeed:" + BaseMoveSpeed + ","
        + "MaxWaitTime:" + MaxWaitTime + ","
        + "MaxConsecutiveDisappointment:" + MaxConsecutiveDisappointment + ","
        + "RefreshWeight:" + RefreshWeight + ","
        + "InitSatisfaction:" + InitSatisfaction + ","
        + "InitStayTime:" + Luban.StringUtil.CollectionToString(InitStayTime) + ","
        + "MaxStayTime:" + MaxStayTime + ","
        + "PatienceDecay:" + PatienceDecay + ","
        + "SatisfactionThreshold:" + SatisfactionThreshold + ","
        + "TimeBonus:" + TimeBonus + ","
        + "FallbackEnabled:" + FallbackEnabled + ","
        + "ModelID:" + ModelID + ","
        + "}";
    }
}

}
