
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.zs
{
public partial class TbBuildingLevel
{
    private readonly System.Collections.Generic.Dictionary<int, BuildingLevel> _dataMap;
    private readonly System.Collections.Generic.List<BuildingLevel> _dataList;
    
    public TbBuildingLevel(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, BuildingLevel>();
        _dataList = new System.Collections.Generic.List<BuildingLevel>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            BuildingLevel _v;
            _v = BuildingLevel.DeserializeBuildingLevel(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, BuildingLevel> DataMap => _dataMap;
    public System.Collections.Generic.List<BuildingLevel> DataList => _dataList;

    public BuildingLevel GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public BuildingLevel Get(int key) => _dataMap[key];
    public BuildingLevel this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

