
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.zs
{
public partial class TbBuild
{
    private readonly System.Collections.Generic.Dictionary<int, Build> _dataMap;
    private readonly System.Collections.Generic.List<Build> _dataList;
    
    public TbBuild(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Build>();
        _dataList = new System.Collections.Generic.List<Build>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            Build _v;
            _v = Build.DeserializeBuild(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Build> DataMap => _dataMap;
    public System.Collections.Generic.List<Build> DataList => _dataList;

    public Build GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Build Get(int key) => _dataMap[key];
    public Build this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

