
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.zs
{
public partial class TbQuestCondition
{
    private readonly System.Collections.Generic.Dictionary<int, QuestCondition> _dataMap;
    private readonly System.Collections.Generic.List<QuestCondition> _dataList;
    
    public TbQuestCondition(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, QuestCondition>();
        _dataList = new System.Collections.Generic.List<QuestCondition>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            QuestCondition _v;
            _v = QuestCondition.DeserializeQuestCondition(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, QuestCondition> DataMap => _dataMap;
    public System.Collections.Generic.List<QuestCondition> DataList => _dataList;

    public QuestCondition GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public QuestCondition Get(int key) => _dataMap[key];
    public QuestCondition this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

