
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.zs
{
public partial class TbEmployee
{
    private readonly System.Collections.Generic.Dictionary<int, Employee> _dataMap;
    private readonly System.Collections.Generic.List<Employee> _dataList;
    
    public TbEmployee(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Employee>();
        _dataList = new System.Collections.Generic.List<Employee>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            Employee _v;
            _v = Employee.DeserializeEmployee(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Employee> DataMap => _dataMap;
    public System.Collections.Generic.List<Employee> DataList => _dataList;

    public Employee GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Employee Get(int key) => _dataMap[key];
    public Employee this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

