
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.zs
{
public partial class TbIslandLevel
{
    private readonly System.Collections.Generic.Dictionary<int, IslandLevel> _dataMap;
    private readonly System.Collections.Generic.List<IslandLevel> _dataList;
    
    public TbIslandLevel(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, IslandLevel>();
        _dataList = new System.Collections.Generic.List<IslandLevel>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            IslandLevel _v;
            _v = IslandLevel.DeserializeIslandLevel(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, IslandLevel> DataMap => _dataMap;
    public System.Collections.Generic.List<IslandLevel> DataList => _dataList;

    public IslandLevel GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public IslandLevel Get(int key) => _dataMap[key];
    public IslandLevel this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

