
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.zs
{
public partial class TbGameConfig
{
    private readonly System.Collections.Generic.Dictionary<int, GameConfig> _dataMap;
    private readonly System.Collections.Generic.List<GameConfig> _dataList;
    
    public TbGameConfig(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, GameConfig>();
        _dataList = new System.Collections.Generic.List<GameConfig>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            GameConfig _v;
            _v = GameConfig.DeserializeGameConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.InitialNumberIslands, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, GameConfig> DataMap => _dataMap;
    public System.Collections.Generic.List<GameConfig> DataList => _dataList;

    public GameConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public GameConfig Get(int key) => _dataMap[key];
    public GameConfig this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

