
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.zs
{
public partial class TbBridgeConfig
{
    private readonly System.Collections.Generic.Dictionary<int, BridgeConfig> _dataMap;
    private readonly System.Collections.Generic.List<BridgeConfig> _dataList;
    
    public TbBridgeConfig(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, BridgeConfig>();
        _dataList = new System.Collections.Generic.List<BridgeConfig>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            BridgeConfig _v;
            _v = BridgeConfig.DeserializeBridgeConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, BridgeConfig> DataMap => _dataMap;
    public System.Collections.Generic.List<BridgeConfig> DataList => _dataList;

    public BridgeConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public BridgeConfig Get(int key) => _dataMap[key];
    public BridgeConfig this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

