
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.zs
{
public partial class TbTourist
{
    private readonly System.Collections.Generic.Dictionary<int, Tourist> _dataMap;
    private readonly System.Collections.Generic.List<Tourist> _dataList;
    
    public TbTourist(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Tourist>();
        _dataList = new System.Collections.Generic.List<Tourist>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            Tourist _v;
            _v = Tourist.DeserializeTourist(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.ID, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Tourist> DataMap => _dataMap;
    public System.Collections.Generic.List<Tourist> DataList => _dataList;

    public Tourist GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Tourist Get(int key) => _dataMap[key];
    public Tourist this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

