
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.zs
{
public partial class TbBuildingUnlock
{
    private readonly System.Collections.Generic.Dictionary<int, BuildingUnlock> _dataMap;
    private readonly System.Collections.Generic.List<BuildingUnlock> _dataList;
    
    public TbBuildingUnlock(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, BuildingUnlock>();
        _dataList = new System.Collections.Generic.List<BuildingUnlock>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            BuildingUnlock _v;
            _v = BuildingUnlock.DeserializeBuildingUnlock(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, BuildingUnlock> DataMap => _dataMap;
    public System.Collections.Generic.List<BuildingUnlock> DataList => _dataList;

    public BuildingUnlock GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public BuildingUnlock Get(int key) => _dataMap[key];
    public BuildingUnlock this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

