
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.zs
{
public partial class TbGuideStep
{
    private readonly System.Collections.Generic.Dictionary<int, GuideStep> _dataMap;
    private readonly System.Collections.Generic.List<GuideStep> _dataList;
    
    public TbGuideStep(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, GuideStep>();
        _dataList = new System.Collections.Generic.List<GuideStep>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            GuideStep _v;
            _v = GuideStep.DeserializeGuideStep(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, GuideStep> DataMap => _dataMap;
    public System.Collections.Generic.List<GuideStep> DataList => _dataList;

    public GuideStep GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public GuideStep Get(int key) => _dataMap[key];
    public GuideStep this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

