
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.zs
{
public partial class TbProsperity
{
    private readonly System.Collections.Generic.Dictionary<int, Prosperity> _dataMap;
    private readonly System.Collections.Generic.List<Prosperity> _dataList;
    
    public TbProsperity(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Prosperity>();
        _dataList = new System.Collections.Generic.List<Prosperity>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            Prosperity _v;
            _v = Prosperity.DeserializeProsperity(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Prosperity> DataMap => _dataMap;
    public System.Collections.Generic.List<Prosperity> DataList => _dataList;

    public Prosperity GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Prosperity Get(int key) => _dataMap[key];
    public Prosperity this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

