
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg.zsEnum
{ 
    public enum Star
    {
        /// <summary>
        /// 1星
        /// </summary>
        Star1 = 1,
        /// <summary>
        /// 2星
        /// </summary>
        Star2 = 2,
        /// <summary>
        /// 3星
        /// </summary>
        Star3 = 3,
    }

} 

