
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg.zsEnum
{ 
    public enum UnlockEffect
    {
        /// <summary>
        /// 航站楼建筑泊位数量开放
        /// </summary>
        TerminalBuildingBerthSlotsUnlocked = 1,
        /// <summary>
        /// 开放飞艇种类，填飞艇ID
        /// </summary>
        UnlockedAirshipTypes = 2,
        /// <summary>
        /// 飞艇航班全局周期加速%
        /// </summary>
        GlobalAirshipFlightCycleAcceleration = 3,
        /// <summary>
        /// 航站楼机库数量上限
        /// </summary>
        TerminalHangarCapacityLimit = 4,
        /// <summary>
        /// 解锁建筑大类每种建筑可建数量
        /// </summary>
        UnlockedBuildingCategoriesBuildableQuantityPerType = 5,
        /// <summary>
        /// 解锁建造队列
        /// </summary>
        UnlockedConstructionQueue = 6,
        /// <summary>
        /// 解锁招募栏位
        /// </summary>
        UnlockRecruitmentSots = 7,
    }

} 

