
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg.zsEnum
{ 
    public enum Employeequality
    {
        /// <summary>
        /// 灰领
        /// </summary>
        GreyCollar = 1,
        /// <summary>
        /// 蓝领
        /// </summary>
        BlueCollar = 2,
        /// <summary>
        /// 金领
        /// </summary>
        GoldenCollar = 3,
    }

} 

