
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg.zsEnum
{ 
    public enum Orientation
    {
        /// <summary>
        /// 东北
        /// </summary>
        Northeast = 1,
        /// <summary>
        /// 东南
        /// </summary>
        Southeast = 2,
        /// <summary>
        /// 西南
        /// </summary>
        Southwest = 3,
        /// <summary>
        /// 西北
        /// </summary>
        Northwest = 4,
    }

} 

