
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg.zsEnum
{ 
    public enum IslandBonusType
    {
        /// <summary>
        /// 无加成
        /// </summary>
        Empty = 0,
        /// <summary>
        /// 农场产出加成
        /// </summary>
        FarmProductionBonus = 1,
        /// <summary>
        /// 伐木场产出加成
        /// </summary>
        LumberyardOutputBonus = 2,
        /// <summary>
        /// 采石场产出加成
        /// </summary>
        QuarryOutputBonus = 3,
    }

} 

