
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg.zsEnum
{ 
    public enum BuildingType
    {
        /// <summary>
        /// 核心类
        /// </summary>
        Core = 1,
        /// <summary>
        /// 供给类
        /// </summary>
        Supply = 2,
        /// <summary>
        /// 产出类
        /// </summary>
        Output = 3,
        /// <summary>
        /// 服务类
        /// </summary>
        Service = 4,
        /// <summary>
        /// 体验类
        /// </summary>
        Experience = 5,
        /// <summary>
        /// 公众桥
        /// </summary>
        PublicBridge = 6,
        /// <summary>
        /// 员工桥
        /// </summary>
        StaffBridge = 7,
    }

} 

