
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg.zsEnum
{ 
    public enum ItemType
    {
        /// <summary>
        /// 货币
        /// </summary>
        Currency = 1,
        /// <summary>
        /// 建造材料
        /// </summary>
        ConstructionMaterials = 2,
        /// <summary>
        /// 美食材料
        /// </summary>
        GourmetIngredients = 3,
        /// <summary>
        /// 加速道具
        /// </summary>
        SpeedBoostItem = 4,
        /// <summary>
        /// 燃油
        /// </summary>
        Fuel = 5,
        /// <summary>
        /// 商品
        /// </summary>
        Product = 6,
        /// <summary>
        /// 三消道具
        /// </summary>
        Match3Prop = 101,
        /// <summary>
        /// 三消体力
        /// </summary>
        Match3Stamina = 102,
    }

} 

