
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg.zsEnum
{ 
    public enum AgeGroup
    {
        /// <summary>
        /// 少年
        /// </summary>
        Young = 1,
        /// <summary>
        /// 青年
        /// </summary>
        Youth = 2,
        /// <summary>
        /// 中年
        /// </summary>
        MiddleAged = 3,
        /// <summary>
        /// 老年
        /// </summary>
        Elderly = 4,
    }

} 

