
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg.zsEnum
{ 
    public enum IslandType
    {
        /// <summary>
        /// 空
        /// </summary>
        Non = 0,
        /// <summary>
        /// 草原岛屿
        /// </summary>
        GrasslandIslands = 1,
        /// <summary>
        /// 森林岛屿
        /// </summary>
        ForestIsland = 2,
        /// <summary>
        /// 岩石岛屿
        /// </summary>
        RockyIsland = 3,
        /// <summary>
        /// 水域岛屿
        /// </summary>
        WaterIslands = 4,
    }

} 

