
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg.zsEnum
{ 
    public enum BuildingSubtype
    {
        /// <summary>
        /// 游客中心
        /// </summary>
        VisitorCenter = 1,
        /// <summary>
        /// 航站楼
        /// </summary>
        Terminal = 2,
        /// <summary>
        /// 工程署
        /// </summary>
        EngineeringOffice = 3,
        /// <summary>
        /// 人才市场
        /// </summary>
        TalentMarket = 4,
        /// <summary>
        /// 油田
        /// </summary>
        OilField = 5,
        /// <summary>
        /// 炼油厂
        /// </summary>
        Refinery = 6,
        /// <summary>
        /// 发电站
        /// </summary>
        PowerPlant = 7,
        /// <summary>
        /// 农田
        /// </summary>
        Farmland = 8,
        /// <summary>
        /// 伐木场
        /// </summary>
        LoggingSite = 9,
        /// <summary>
        /// 采石场
        /// </summary>
        Quarry = 10,
        /// <summary>
        /// 畜牧场
        /// </summary>
        LivestockFarm = 11,
        /// <summary>
        /// 夜市轻食摊
        /// </summary>
        NightMarketSnackStall = 12,
        /// <summary>
        /// 森林茶屋
        /// </summary>
        ForestTeahouse = 13,
        /// <summary>
        /// 石窑披萨坊
        /// </summary>
        StoneOvenPizzeria = 14,
        /// <summary>
        /// 手冲咖啡站
        /// </summary>
        HandBrewCoffeeStand = 15,
        /// <summary>
        /// 海风果汁吧
        /// </summary>
        SeaBreezeJuiceBar = 16,
        /// <summary>
        /// 浮桥海鲜档
        /// </summary>
        FloatingPierSeafoodStall = 17,
        /// <summary>
        /// 悬挑天境台
        /// </summary>
        CantileverSkyTerrace = 18,
        /// <summary>
        /// 林梢环形秋千
        /// </summary>
        TreeTopCircularSwing = 19,
        /// <summary>
        /// 岩顶观景台
        /// </summary>
        RockyPeakViewingDeck = 20,
        /// <summary>
        /// 解谜小屋
        /// </summary>
        PuzzleCabin = 21,
        /// <summary>
        /// 森林绳索乐园
        /// </summary>
        ForestRopePark = 22,
        /// <summary>
        /// 星空露天影院
        /// </summary>
        StarrySkyOutdoorCinema = 23,
        /// <summary>
        /// 玻璃底观景舱
        /// </summary>
        GlassBottomViewingPod = 24,
        /// <summary>
        /// 海风音乐露台
        /// </summary>
        UnderseaViewingDome = 25,
        /// <summary>
        /// 普通员工桥
        /// </summary>
        EmployeeBridge = 601,
        /// <summary>
        /// 普通游客桥
        /// </summary>
        TouristBridge = 701,
    }

} 

