
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg.zsEnum
{ 
    public enum Gender
    {
        /// <summary>
        /// 男
        /// </summary>
        Man = 1,
        /// <summary>
        /// 女
        /// </summary>
        Woman = 2,
    }

} 

