
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg.zsEnum
{ 
    public enum Profession
    {
        /// <summary>
        /// 无职业
        /// </summary>
        Empty = 0,
        /// <summary>
        /// 采油工
        /// </summary>
        Oilman = 201,
        /// <summary>
        /// 炼油厂操作员
        /// </summary>
        RefineryOperator = 202,
        /// <summary>
        /// 电力工程师
        /// </summary>
        PowerEngineer = 203,
        /// <summary>
        /// 农夫
        /// </summary>
        Farmer = 301,
        /// <summary>
        /// 伐木工
        /// </summary>
        Logger = 302,
        /// <summary>
        /// 矿工
        /// </summary>
        Miner = 303,
        /// <summary>
        /// 畜牧员
        /// </summary>
        Rancher = 304,
        /// <summary>
        /// 夜市轻食摊售卖员
        /// </summary>
        SnackVendor = 401,
        /// <summary>
        /// 茶师
        /// </summary>
        TeaMaster = 402,
        /// <summary>
        /// 披萨师
        /// </summary>
        Pizzaiolo = 403,
        /// <summary>
        /// 咖啡师
        /// </summary>
        Barista = 404,
        /// <summary>
        /// 果汁吧售卖员
        /// </summary>
        JuiceVendor = 405,
        /// <summary>
        /// 海鲜档售卖员
        /// </summary>
        SeafoodVendor = 406,
        /// <summary>
        /// 天镜台引导员
        /// </summary>
        SkyMirrorAttendant = 501,
        /// <summary>
        /// 林梢环形秋千操作员
        /// </summary>
        CanopySwingOperator = 502,
        /// <summary>
        /// 岩顶观景导览员
        /// </summary>
        CliffViewGuide = 503,
        /// <summary>
        /// 解谜小屋主持
        /// </summary>
        PuzzleCabinHost = 504,
        /// <summary>
        /// 绳索乐园教练
        /// </summary>
        RopeParkCoach = 505,
        /// <summary>
        /// 星空露天影院运营员
        /// </summary>
        StarlitCinemaOperator = 506,
        /// <summary>
        /// 玻璃底观景舱导览员
        /// </summary>
        GlassPodGuide = 507,
        /// <summary>
        /// 海底观景穹顶导览员
        /// </summary>
        UnderseaDomeGuide = 508,
    }

} 

